language: ruby
rvm: 2.2.5
sudo: false
dist: trusty
branches:
  only:
  - develop
env:
  secure: jw6dUUvb+eztJxBOTf40cT/M/xhOZtUBdYQTV2alipnhaurO30ifpc1507kE1DhNzRQ04VZ/KSa9KWv3ewgigoC7vA+FtwDhS73a5xF3pB/uCKB68NWdVdgCF23K5udjsYXbBN7aBbree4Nuwg/fXHsuBAmR0tnxE8PZ7fb8ETbSVUd6xe72HK0riU1Wc6rxCkE4JAM7H8GE7m+lxq4M0tQ7VKBQYypA9ZTRe3Fvx0Mdks/OHE7TZf6LVVmNkANQeloRY0yD4lhrPGJkOdRFtBJBxlKe5Il9nQNeJIJt7bZbZdmRL8vuMjWudhJOiN7awDTA8LndI1kE1D1kDcaZGrzlsbONBVUQBPOh8PKcH5DC1N3gsIboRJOf6a116FUDnaUZYnndbA7Gqdm44U0KToCeIu3tFrJcpU3LTQ7EQGQcx+sNR8ORPqvxehTFX5pVGnqVfBE+VS9PthkHJJZ6X5xukLA/SWFGYQRgl+dXB1J6y8Row679XizVQhCjsEImWa9FQgO04SUcwPrwLTBdSkTZDENQCzu+HWqmTOOVItAEOqV1K2146Pl2abtimn96Ruc8Mr/eFacvWAn3wEPrkDYf97Iy5YFq67rQMkkn69/yoLeeiCQmInr0qcQSUVq6fQ1VFQKMywCHhWr+NW3BHHrFiDGvITDX0btWI1u8Slk=
install: gem install jekyll jekyll-paginate rake
script: rake
deploy:
  provider: pages
  local-dir: _site
  target-branch: master
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  verbose: true
  on:
    branch:
    - develop
