# Site settings
title: Home | SinglePayerNOW

description: Future home for the sebsite behind SinglePayerNOW
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.io/wheelerlaw/spn" # the base hostname & protocol for your site

permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown

paginate: 5
plugins: [jekyll-paginate]
exclude:
 - package.json
 - README.md
 - node_modules
 - scripts
 - .travis.yml
 - Rakefile
 - local

collections:
  projects:
    output: true
version: 0.1
